title: taxiboatdriver
description: >
  Minimalistic homepage for taxiboatdriver.com

# theme: jekyll-theme-hacker    # <- If only it could bless us with a better list style
theme: jekyll-theme-architect
